from pathlib import Path

from .config import BASE_DIR, ENROLL_DIR, VAL_DIR, TEST_DIR, UNKNOWN_DIR

FINETUNE_ARTIFACTS_DIR = BASE_DIR / "artifacts_finetuned"
FINETUNE_CHECKPOINTS_DIR = FINETUNE_ARTIFACTS_DIR / "checkpoints"
FINETUNE_EMBEDDINGS_DIR = FINETUNE_ARTIFACTS_DIR / "embeddings"
FINETUNE_METRICS_DIR = FINETUNE_ARTIFACTS_DIR / "metrics"
FINETUNE_LOGS_DIR = FINETUNE_ARTIFACTS_DIR / "logs"

FINETUNE_IMAGE_SIZE = 112
FINETUNE_BATCH_SIZE = 16
FINETUNE_NUM_EPOCHS = 12
FINETUNE_LR = 1e-3
FINETUNE_WEIGHT_DECAY = 1e-4
FINETUNE_EMBED_DIM = 256
FINETUNE_FREEZE_BACKBONE = True
FINETUNE_UNFREEZE_LAST_BLOCK = True
FINETUNE_MODEL_NAME = "resnet18"

for d in [
    FINETUNE_ARTIFACTS_DIR,
    FINETUNE_CHECKPOINTS_DIR,
    FINETUNE_EMBEDDINGS_DIR,
    FINETUNE_METRICS_DIR,
    FINETUNE_LOGS_DIR,
]:
    d.mkdir(parents=True, exist_ok=True)
